from ninja import Schema


class TokenSchema(Schema):
    """
    Token Schema for the response of the login endpoint for the user authentication.

    The fields defined here are:
    - token: a string containing the token generated by the server.
    """

    token: str
