# Generated by Django 5.1.2 on 2024-10-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_rename_user_comment_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="answer_to",
            new_name="parent",
        ),
    ]
